### ISSUE TITLE
Bug: getIPInfo method breaks

### ISSUE THREAD

**Issue by aoor9** [pariazar/ip-info-finder#3]
### Environment
Node version: v16.18.1
pnpm version: v7.29.0
Operating System: linux

### What did you do?
`await ipInfo.getIPInfo(any_ip_v4_address);`

### What did you expect to happen?
It should always return the result, no matter how many times I call it.

### What actually happened?
If I invoke it once, it works. But if I call it twice in the same runtime (by copying the same instruction next)...
```
.../node_modules/.pnpm/ip-info-finder@3.0.1/node_modules/ip-info-finder/index.js:43
  const populationResult = population.filter((item) => item.country.includes(response.Country.split('(')[0].trim()));
                                                                    ^

TypeError: Cannot read properties of undefined (reading 'includes')
    at .../node_modules/.pnpm/ip-info-finder@3.0.1/node_modules/ip-info-finder/index.js:43:69
    at Array.filter (<anonymous>)
    ...
```

**Comment by pariazar** [comment]
Hello,

You are correct that there is a bug that displays the population for a country. Thank you for reporting this issue. The bug has been fixed in version 3.0.2.

Best regards.
